name: scalers
description: "A Flutter project for Scalers"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.5.7




  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  json_annotation: ^4.9.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed_annotation: ^2.2.0
  flutter_lints: ^4.0.0
flutter:


  uses-material-design: true

